### ISSUE TITLE
Case: new case creation loses the petition type if I select it with arrow and tab from list

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#13]
I think this might be in the old bug list, but it's still there.

**Comment by douglaswyatt** [comment]
The same bug happens on the Case Edit page, if I select the petition type with arrow and tab, it doesn't stick.  I have to click on it from the list for it to stick.

**Comment by adityadigitalomnibus** [comment]
fixed

**Comment by douglaswyatt** [comment]
Still a bug for me.  And also see bug #23

**Comment by adityadigitalomnibus** [comment]
It may be a caching issue. I request you to clear your cache. Follow the instructions on this page - 
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WJIzj_F948q

**Comment by douglaswyatt** [comment]
Still a problem.  I recreated it as doug@hlrn.org in Chrome and as Aditya in FireFox:

![screen shot 2017-02-13 at 5 27 59 pm](https://cloud.githubusercontent.com/assets/23498712/22882649/26f1acbc-f212-11e6-8673-4c7ceddfd4ab.png)
![screen shot 2017-02-13 at 5 28 25 pm](https://cloud.githubusercontent.com/assets/23498712/22882650/26f3d37a-f212-11e6-85cf-0881f0962036.png)
![screen shot 2017-02-13 at 5 29 44 pm](https://cloud.githubusercontent.com/assets/23498712/22882651/26f58e4a-f212-11e6-8110-730aaf199427.png)
![screen shot 2017-02-13 at 5 29 58 pm](https://cloud.githubusercontent.com/assets/23498712/22882648/26f02374-f212-11e6-85fd-adcdd8350652.png)

**Comment by douglaswyatt** [comment]
The problem is that hitting tab leaves the text there and changes field focus, making the user think it worked.  Solution is either for tab to make it stick, but if that isn't possible then make Tab not leave the text in the field and change focus, so the user doesn't think they successfully selected the item.

**Comment by douglaswyatt** [comment]
Not perfect - since it'd be better of Tab would actually select the value (like clicking or hitting return does) but at least now it doesn't trick the user in to thinking that they've entered a value which won't stick.  But it would be nice to see if Tab can be made to actually select the value as this is pretty standard UI behaviour so people may be trained to do it.
