### ISSUE TITLE
Cases/Activities:for some users it appears that the Show All Case and Activity list is limited to cases/activities owned by them. 

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#22]
Found this when logged in as Kabir.   IT should show all cases/activities regardless of Owner.  Only the Profile page Case/Activity list should be filtered by Owner.  For Douglas, the "show all Activities" link shows two (his and Kabir's). But I know there are more (i.e. one owned by Aditya).

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 11 57 10 am](https://cloud.githubusercontent.com/assets/23498712/21494913/93da237a-cc3a-11e6-8f72-cedc30074274.png)

**Comment by adityadigitalomnibus** [comment]
fixed

**Comment by douglaswyatt** [comment]
not fixed

**Comment by douglaswyatt** [comment]
This is still open.  For instance, here is what I see when I log in as Doug and go to the Activity View page.  For what it's worth, it's not just showing my own activities.  It's only showing three activities, but I'm not sure why it picks these three.  Another bug (showing more Activities than it should on the Profile My Open Activities table) makes it clear that there are a lot more than 3 activities int he system.

![screen shot 2017-01-23 at 11 03 14 am](https://cloud.githubusercontent.com/assets/23498712/22192665/da7b6484-e15b-11e6-9372-aa67ede46018.png)

**Comment by douglaswyatt** [comment]
I still see this bug.  Aditya (an admin) seems to see all the activities (~12), but Doug and Olivia do not.  Olivia sees no activites (and owns no activities), while Doug sees 3 - two owned by him and one owned by Kabir.

**Comment by douglaswyatt** [comment]
(and, by the way, I see this on my iPad as well, which I've never used to connect before, so I know it's not a caching issue)
