### ISSUE TITLE
General: many auto-complete form-field lists populate their fields with the text of an entry when I use arrow-down and tab to select it, but they don't "stick" when I submit the form.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#23]
For instance, if I type "do" in the Additional Owner field of an Activity, the list includes (among other users) "doug@hrln.org".  If I arrow down to that entry and hit tab, it fills in "doug@hrln.org" in the field, and move the focus to the next field.  But if I add the Activity, it does not include "doug@hrln.org" as an additional owner.

Ive logged a few of these before, but this seems like a system-wide problem that might need a system-wide fix (and certainly system-wide QA).  In particular, I've seen this with:

Petition Type
Activity Primary Unit (but which should be titled Primary Group)
Additional Owner
Update Additional PArticipant

But it would be good if you all could to a comprehensive test of all fields to make sure they all work properly (or figure out why the default widget you're using is working incorrectly).

**Comment by adityadigitalomnibus** [comment]
fixed

**Comment by douglaswyatt** [comment]
not fixed

**Comment by adityadigitalomnibus** [comment]
caching issue. clear the cache

**Comment by douglaswyatt** [comment]
Not fixed.  Tried it again and all 4 fields do not "stick" if I've selected them with arrow down and then tab (using Chrome).

**Comment by douglaswyatt** [comment]
The problem is that hitting tab leaves the text there and changes field focus, making the user think it worked.  Solution is either for tab to make it stick, but if that isn't possible then make Tab not leave the text in the field and change focus, so the user doesn't think they successfully selected the item.

**Comment by douglaswyatt** [comment]
Not perfect - since it'd be better of Tab would actually select the value (like clicking or hitting return does) but at least now it doesn't trick the user in to thinking that they've entered a value which won't stick.  But it would be nice to see if Tab can be made to actually select the value as this is pretty standard UI behaviour so people may be trained to do it.
